# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Sync only specific branches from Azure DevOps

pool: SelfHostedAgent

steps:
- checkout: self  # Check out the Azure DevOps repo

- script: |
    git remote add github https://github.com/yogeshkarpe-dot/LearnIT.git
    git push --mirror github
  displayName: 'Push changes from Azure DevOps to GitHub'

