# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: SelfHostedAgent

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'  # Use the .NET 8 SDK version as needed

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      if (-not (Test-Path .git)) {
        git init
      }

      $remotes = git remote
      if (-not $remotes.Contains('origin')) {
        git remote add origin https://$(gitHubUsername):$(gitHubPat)@github.com/yogeshkarpe-dot/learnit-api.git
      }

      git fetch origin

      git config --global user.name 'Yogesh Karpe'

      git checkout master -ErrorAction SilentlyContinue
      if ($?) {
        git checkout -b master
      }

      git add .
      if (git diff --cached --quiet) {
        Write-Host 'No changes to commit.'
      } else {
        git commit -m 'Automated push from Azure DevOps pipeline'
        git push -u origin master
      }
  displayName: 'Push code to GitHub repository'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: Container