# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main  # Or the branch you want to sync to GitHub

resources:
  repositories:
    - repository: GitHubRepo
      type: github
      endpoint: 'github.com_yogeshkarpe-dot' # Name of the GitHub service connection in Azure DevOps
      name: 'yogeshkarpe-dot/LearnIT' # Full GitHub repository name

pool: SelfHostedAgent

steps:
  - checkout: self
    displayName: 'Checkout Azure DevOps repository'

  - task: Bash@3
    displayName: 'Define GitHub remote URL and pull latest changes'
    inputs:
      targetType: 'inline'
      script: |
        GITHUB_URL=$(resources.repositories.GitHubRepo.url)
        git remote add github $GITHUB_URL
        git pull github main  # Adjust branch as needed

  - script: |
      echo "Run any build, test, or modification steps here"
    displayName: 'Build or Modify Code'

  - task: Bash@3
    displayName: 'Push changes to GitHub repository'
    inputs:
      targetType: 'inline'
      script: |
        git push github main  # Pushes changes from Azure DevOps to GitHub

